---
- name: Deploy dns server to install docker
  gather_facts: true
  hosts: host01
  become: yes
  tasks:
  - set_fact: ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa
  - include: tasks/main.yml
